// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240827175158_NewUodate")]
    partial class NewUodate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentRegNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            PhoneNumber = "+998901234567",
                            StudentRegNumber = "STU10001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PhoneNumber = "+998901234568",
                            StudentRegNumber = "STU10002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie.brown@example.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            PhoneNumber = "+998901234569",
                            StudentRegNumber = "STU10003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.prince@example.com",
                            FirstName = "Diana",
                            LastName = "Prince",
                            PhoneNumber = "+998901234570",
                            StudentRegNumber = "STU10004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2003, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eva.green@example.com",
                            FirstName = "Eva",
                            LastName = "Green",
                            PhoneNumber = "+998901234571",
                            StudentRegNumber = "STU10005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2004, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "frank.moore@example.com",
                            FirstName = "Frank",
                            LastName = "Moore",
                            PhoneNumber = "+998901234572",
                            StudentRegNumber = "STU10006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2005, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.lee@example.com",
                            FirstName = "Grace",
                            LastName = "Lee",
                            PhoneNumber = "+998901234573",
                            StudentRegNumber = "STU10007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2006, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hannah.wilson@example.com",
                            FirstName = "Hannah",
                            LastName = "Wilson",
                            PhoneNumber = "+998901234574",
                            StudentRegNumber = "STU10008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2007, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ian.taylor@example.com",
                            FirstName = "Ian",
                            LastName = "Taylor",
                            PhoneNumber = "+998901234575",
                            StudentRegNumber = "STU10009"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2008, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jasmine.anderson@example.com",
                            FirstName = "Jasmine",
                            LastName = "Anderson",
                            PhoneNumber = "+998901234576",
                            StudentRegNumber = "STU10010"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.white@example.com",
                            FirstName = "Kevin",
                            LastName = "White",
                            PhoneNumber = "+998901234577",
                            StudentRegNumber = "STU10011"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2000, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.harris@example.com",
                            FirstName = "Laura",
                            LastName = "Harris",
                            PhoneNumber = "+998901234578",
                            StudentRegNumber = "STU10012"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1999, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.clark@example.com",
                            FirstName = "Michael",
                            LastName = "Clark",
                            PhoneNumber = "+998901234579",
                            StudentRegNumber = "STU10013"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2002, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "natalie.martinez@example.com",
                            FirstName = "Natalie",
                            LastName = "Martinez",
                            PhoneNumber = "+998901234580",
                            StudentRegNumber = "STU10014"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.garcia@example.com",
                            FirstName = "Oscar",
                            LastName = "Garcia",
                            PhoneNumber = "+998901234581",
                            StudentRegNumber = "STU10015"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2004, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul.rodriguez@example.com",
                            FirstName = "Paul",
                            LastName = "Rodriguez",
                            PhoneNumber = "+998901234582",
                            StudentRegNumber = "STU10016"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2005, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn.lewis@example.com",
                            FirstName = "Quinn",
                            LastName = "Lewis",
                            PhoneNumber = "+998901234583",
                            StudentRegNumber = "STU10017"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2006, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rachel.walker@example.com",
                            FirstName = "Rachel",
                            LastName = "Walker",
                            PhoneNumber = "+998901234584",
                            StudentRegNumber = "STU10018"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(2007, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "samuel.hall@example.com",
                            FirstName = "Samuel",
                            LastName = "Hall",
                            PhoneNumber = "+998901234585",
                            StudentRegNumber = "STU10019"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2008, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tina.allen@example.com",
                            FirstName = "Tina",
                            LastName = "Allen",
                            PhoneNumber = "+998901234586",
                            StudentRegNumber = "STU10020"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(2001, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "uma.young@example.com",
                            FirstName = "Uma",
                            LastName = "Young",
                            PhoneNumber = "+998901234587",
                            StudentRegNumber = "STU10021"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(2000, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor.king@example.com",
                            FirstName = "Victor",
                            LastName = "King",
                            PhoneNumber = "+998901234588",
                            StudentRegNumber = "STU10022"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1999, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "wendy.wright@example.com",
                            FirstName = "Wendy",
                            LastName = "Wright",
                            PhoneNumber = "+998901234589",
                            StudentRegNumber = "STU10023"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2002, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "xavier.lopez@example.com",
                            FirstName = "Xavier",
                            LastName = "Lopez",
                            PhoneNumber = "+998901234590",
                            StudentRegNumber = "STU10024"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(2003, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasmin.hill@example.com",
                            FirstName = "Yasmin",
                            LastName = "Hill",
                            PhoneNumber = "+998901234591",
                            StudentRegNumber = "STU10025"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2004, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zachary.scott@example.com",
                            FirstName = "Zachary",
                            LastName = "Scott",
                            PhoneNumber = "+998901234592",
                            StudentRegNumber = "STU10026"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2005, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amelia.adams@example.com",
                            FirstName = "Amelia",
                            LastName = "Adams",
                            PhoneNumber = "+998901234593",
                            StudentRegNumber = "STU10027"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(2006, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brian.nelson@example.com",
                            FirstName = "Brian",
                            LastName = "Nelson",
                            PhoneNumber = "+998901234594",
                            StudentRegNumber = "STU10028"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(2007, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chloe.carter@example.com",
                            FirstName = "Chloe",
                            LastName = "Carter",
                            PhoneNumber = "+998901234595",
                            StudentRegNumber = "STU10029"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(2008, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.mitchell@example.com",
                            FirstName = "Daniel",
                            LastName = "Mitchell",
                            PhoneNumber = "+998901234596",
                            StudentRegNumber = "STU10030"
                        });
                });

            modelBuilder.Entity("API.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Grade")
                        .HasColumnType("REAL");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            Grade = 88.0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            Grade = 78.0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            Grade = 82.0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 4,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            Grade = 88.0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 4,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 5,
                            Grade = 77.0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            Grade = 75.0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            Grade = 100.0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            Grade = 80.0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 7,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 8,
                            Grade = 80.0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            Grade = 86.0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 3,
                            Grade = 82.0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 2,
                            Grade = 88.0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 4,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 5,
                            Grade = 75.0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 6,
                            Grade = 87.0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 1,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 2,
                            Grade = 100.0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 5,
                            Grade = 77.0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 1,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 3,
                            Grade = 82.0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 4,
                            Grade = 84.0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 3,
                            Grade = 82.0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 2,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 5,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 6,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 1,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 3,
                            Grade = 83.0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 2,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 5,
                            Grade = 84.0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 4,
                            Grade = 77.0
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 1,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 7,
                            Grade = 93.0
                        },
                        new
                        {
                            StudentId = 13,
                            SubjectId = 8,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 4,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 3,
                            Grade = 87.0
                        },
                        new
                        {
                            StudentId = 14,
                            SubjectId = 6,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 2,
                            Grade = 82.0
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 1,
                            Grade = 87.5
                        },
                        new
                        {
                            StudentId = 15,
                            SubjectId = 5,
                            Grade = 78.0
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 3,
                            Grade = 80.0
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 4,
                            Grade = 97.200000000000003
                        },
                        new
                        {
                            StudentId = 16,
                            SubjectId = 2,
                            Grade = 84.0
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 6,
                            Grade = 99.099999999999994
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 7,
                            Grade = 89.0
                        },
                        new
                        {
                            StudentId = 17,
                            SubjectId = 3,
                            Grade = 91.0
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 8,
                            Grade = 76.0
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 4,
                            Grade = 100.0
                        },
                        new
                        {
                            StudentId = 18,
                            SubjectId = 2,
                            Grade = 87.0
                        },
                        new
                        {
                            StudentId = 19,
                            SubjectId = 5,
                            Grade = 90.0
                        },
                        new
                        {
                            StudentId = 19,
                            SubjectId = 1,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 19,
                            SubjectId = 6,
                            Grade = 98.099999999999994
                        },
                        new
                        {
                            StudentId = 20,
                            SubjectId = 3,
                            Grade = 81.0
                        },
                        new
                        {
                            StudentId = 20,
                            SubjectId = 7,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 20,
                            SubjectId = 8,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 21,
                            SubjectId = 6,
                            Grade = 90.0
                        },
                        new
                        {
                            StudentId = 21,
                            SubjectId = 4,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 21,
                            SubjectId = 2,
                            Grade = 87.0
                        },
                        new
                        {
                            StudentId = 22,
                            SubjectId = 3,
                            Grade = 91.0
                        },
                        new
                        {
                            StudentId = 22,
                            SubjectId = 8,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 22,
                            SubjectId = 7,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 23,
                            SubjectId = 5,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 23,
                            SubjectId = 1,
                            Grade = 89.0
                        },
                        new
                        {
                            StudentId = 23,
                            SubjectId = 4,
                            Grade = 80.0
                        },
                        new
                        {
                            StudentId = 24,
                            SubjectId = 2,
                            Grade = 97.900000000000006
                        },
                        new
                        {
                            StudentId = 24,
                            SubjectId = 3,
                            Grade = 78.0
                        },
                        new
                        {
                            StudentId = 24,
                            SubjectId = 6,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 25,
                            SubjectId = 8,
                            Grade = 80.0
                        },
                        new
                        {
                            StudentId = 25,
                            SubjectId = 7,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 25,
                            SubjectId = 5,
                            Grade = 84.0
                        },
                        new
                        {
                            StudentId = 26,
                            SubjectId = 1,
                            Grade = 90.0
                        },
                        new
                        {
                            StudentId = 26,
                            SubjectId = 3,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 26,
                            SubjectId = 6,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 27,
                            SubjectId = 4,
                            Grade = 87.0
                        },
                        new
                        {
                            StudentId = 27,
                            SubjectId = 2,
                            Grade = 98.0
                        },
                        new
                        {
                            StudentId = 27,
                            SubjectId = 1,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 28,
                            SubjectId = 7,
                            Grade = 92.0
                        },
                        new
                        {
                            StudentId = 28,
                            SubjectId = 5,
                            Grade = 99.0
                        },
                        new
                        {
                            StudentId = 28,
                            SubjectId = 8,
                            Grade = 81.0
                        },
                        new
                        {
                            StudentId = 29,
                            SubjectId = 3,
                            Grade = 83.0
                        },
                        new
                        {
                            StudentId = 29,
                            SubjectId = 4,
                            Grade = 85.0
                        },
                        new
                        {
                            StudentId = 29,
                            SubjectId = 2,
                            Grade = 100.0
                        },
                        new
                        {
                            StudentId = 30,
                            SubjectId = 1,
                            Grade = 88.0
                        },
                        new
                        {
                            StudentId = 30,
                            SubjectId = 5,
                            Grade = 79.0
                        },
                        new
                        {
                            StudentId = 30,
                            SubjectId = 6,
                            Grade = 99.599999999999994
                        });
                });

            modelBuilder.Entity("API.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Computer Science"
                        });
                });

            modelBuilder.Entity("API.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1975, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "+998901234567"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1940, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "+998912345678"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1955, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.johnson@example.com",
                            FirstName = "Robert",
                            LastName = "Johnson",
                            PhoneNumber = "+998933456789"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1990, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            PhoneNumber = "+998944567890"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.wilson@example.com",
                            FirstName = "Michael",
                            LastName = "Wilson",
                            PhoneNumber = "+998955678901"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2000, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.taylor@example.com",
                            FirstName = "Sarah",
                            LastName = "Taylor",
                            PhoneNumber = "+998966789012"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1978, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            PhoneNumber = "+998977890123"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1982, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.miller@example.com",
                            FirstName = "Laura",
                            LastName = "Miller",
                            PhoneNumber = "+998988901234"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1987, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.wilson@example.com",
                            FirstName = "James",
                            LastName = "Wilson",
                            PhoneNumber = "+998999012345"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1992, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.moore@example.com",
                            FirstName = "Olivia",
                            LastName = "Moore",
                            PhoneNumber = "+998901234567"
                        });
                });

            modelBuilder.Entity("API.Entities.TeacherSubject", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            TeacherId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            TeacherId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            TeacherId = 4,
                            SubjectId = 4
                        },
                        new
                        {
                            TeacherId = 5,
                            SubjectId = 5
                        },
                        new
                        {
                            TeacherId = 6,
                            SubjectId = 6
                        },
                        new
                        {
                            TeacherId = 7,
                            SubjectId = 7
                        },
                        new
                        {
                            TeacherId = 8,
                            SubjectId = 8
                        },
                        new
                        {
                            TeacherId = 9,
                            SubjectId = 9
                        },
                        new
                        {
                            TeacherId = 10,
                            SubjectId = 10
                        });
                });

            modelBuilder.Entity("API.Entities.StudentSubject", b =>
                {
                    b.HasOne("API.Entities.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("API.Entities.TeacherSubject", b =>
                {
                    b.HasOne("API.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("API.Entities.Student", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("API.Entities.Subject", b =>
                {
                    b.Navigation("StudentSubjects");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("API.Entities.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
